#!/bin/bash
export GITHUB_TOKEN=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

# Configure Git to use the token for accessing private repositories
git config --global url."https://$GITHUB_TOKEN:@github.com/".insteadOf "https://github.com/"

# Additional commands if needed (like pulling a private repository)
git clone https://github.com/wuld666/my-first-binder
